name: Build & Deploy Dragd (lazy)

on:
  push:
    branches:
      - "main"

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: dragd:latest
          secrets: |
            "BASE_SITE=index"
            "MONGO_STRING={{ secrets.MONGO_CONNECTION_STRING }}"
          outputs: type=docker,dest=/tmp/dragd.tar
      - name: Upload docker file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_2 }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "/tmp/dragd.tar"
          target: "/root"
