name: Build & Deploy Dragd

on:
  push:
    branches:
      - "main"

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Dragd
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: metadatalabs/dragd-images:v2.0.0
      - name: Deploy Dragd v2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop dragd
            docker rm dragd
            docker image rm -f metadatalabs/dragd-images:v2.0.0
            docker run --net="host" -d --name="dragd" metadatalabs/dragd-images:v2.0.0
